FROM pythondp

ARG ARTIFACT
ARG VERSION

WORKDIR /tmp
ENV LC_ALL=en_US.utf8

ADD $ARTIFACT.tar.gz /tmp/
RUN ls -l /tmp/
RUN mv $ARTIFACT /application

WORKDIR /application

RUN pyvenv /appenv && . /appenv/bin/activate && pip install -U pip  && \
	pip wheel -r deps.txt && \
    pip install -U -r deps.txt

ENV MODULE=$ARTIFACT
ADD run.sh .
RUN chmod +x run.sh
ENTRYPOINT ["./run.sh", "--conf", "./config.json"]
